"""initial schema

Revision ID: dc240ff6c192
Revises: 
Create Date: 2026-08-04 00:59:38.132114
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc240ff6c192'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('enrollment_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('incarnation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('epoch_floor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('certificate_pem', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(length=253), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('active_session_id', sa.String(length=128), nullable=True),
    sa.Column('fencing_epoch', sa.Integer(), nullable=False),
    sa.Column('incarnation', sa.Integer(), nullable=False),
    sa.Column('highest_sequence', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('desired_generation', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('stop_authorizations',
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('engine_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('node_id', 'engine_id')
    )
    op.create_table('desired_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'generation', name='uq_node_generation')
    )
    op.create_table('observations',
    sa.Column('node_id', sa.String(length=128), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('observation', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('desired_snapshots')
    op.drop_table('stop_authorizations')
    op.drop_table('nodes')
    op.drop_table('incarnation')
    op.drop_table('enrollment_tokens')
    op.drop_table('claims')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
