{{- if .Values.keysSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-keys" (include "meridian.fullname" .)) .Values.keysSecret.name }}
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.keysSecret.stringData }}
  {{ $k }}: |
    {{- $v | nindent 4 }}
  {{- end }}
{{- end }}
